# builder image
FROM golang:1.24-bookworm AS builder

ARG COMMIT
ARG VERSION

WORKDIR /bera-geth

COPY . .

RUN go mod download

RUN go run build/ci.go install -static -git-tag="$VERSION" -git-commit="$COMMIT" ./cmd/bera-geth

FROM ubuntu:24.04

RUN apt-get update && apt-get install -y ca-certificates wget libsnappy-dev libjemalloc-dev

WORKDIR /app

COPY --from=builder /bera-geth/build/bin/bera-geth /usr/bin

EXPOSE 8545 8546 33688 33688/udp

ENTRYPOINT ["/usr/bin/bera-geth"]